pipeline {
  agent any

  stages {
    stage('Install dependencies') {
      steps {
        dir('Playwright-UnoDe50') {
          script {
            if (isUnix()) {
              sh 'npm ci'
            } else {
              bat 'npm ci'
            }
          }
        }
      }
    }

    stage('Install Playwright') {
      steps {
        dir('Playwright-UnoDe50') {
          script {
            if (isUnix()) {
              sh 'npx playwright install --with-deps'
            } else {
              bat 'npx playwright install --with-deps'
            }
          }
        }
      }
    }

    stage('Run Playwright tests') {
      steps {
        dir('Playwright-UnoDe50') {
          script {
            if (isUnix()) {
              sh 'npx playwright test'
            } else {
              bat 'npx playwright test'
            }
          }
        }
      }
    }
  }

  post {
  always {
    def buildReportDir = "Playwright-UnoDe50/playwright-report-${env.BUILD_NUMBER}"
    bat "xcopy /E /I /Y Playwright-UnoDe50\\playwright-report ${buildReportDir}"
    publishHTML(target: [
      reportDir: "${buildReportDir}",
      reportFiles: 'index.html',
      reportName: "Playwright Report - Build ${env.BUILD_NUMBER}",
      keepAll: true,
      alwaysLinkToLastBuild: true,
      allowMissing: true
    ])
  }
}
}