class Locators:
    cookie_accept_id = "onetrust-accept-btn-handler"
    new_members_close_pop_up = "close-popup"
    account_icon_button = "div[class='hidden-xs-down'] i[class='icon-user']"
    email_id = "login-form-email"
    password_id = "login-form-password"
    remember_access_box_cssSelector = "label[for='rememberMe']"
    email = "selene_venus_in_the_sky@outlook.it"
    password = "Venusinthesky89!"
    wrong_email = "dalfonsolucia@hotmail.it"
    wrong_password = "Luckystark95!"
    accedi_button_cssSelector = "#login > form > button"
    alert_message_cssSelector_wrong_email = "#login > form > div.alert.alert-danger"
    error_message_wrong_password_cssSelector = "#maincontent > div.container.error-page-content > div:nth-child(1) > div > h2"
    account_page_cssSelector = ".profile-header"
    account_name_cssSelector = "div[id='myaccount'] span[class='user-message']"
    account_list_cssSelector = "ul[aria-label='Navigazione del mio account'] a"
    home_page_back_cssSelector = "a[aria-current='page']"
    register_tab_cssSelector = "#register-tab"
    insert_name_id = "registration-form-fname"
    insert_surname_id = "registration-form-lname"
    insert_phone_number_id = "registration-form-phone"
    insert_birthday_date_id = "birthday"
    insert_email_id = "registration-form-email"
    insert_password_id = "registration-form-password"
    insert_confirm_password_id = "registration-form-password-confirm"
    insert_gender_id = "female"
    ring_id = "anillos"
    sub_category_xpath = "//a[contains(@href, '/anelli/anelli-dargento/')]"
    product_size_selector = "product-sizes__selector"
    insert_new_members_welcome_cssSelector = "label[for='acceptcommunications']"
    insert_privacy_policy_cssSelector = "label[for='acceptprivacy']"
    click_create_account_button_cssSelector = "#register > form > button"
    logo_uno_de_50_cssSelector = ".logo-home"
    product_pid = "ANI0849_PLATEADO"
    ring_size = "15"
    add_to_cart_className = "add-to-cart"
    cart_icon_cssSelector = "div.minicart"
    view_cart_cssSelector = "div[class='navbar-header-item row mx-0'] a[title='Visualizza carrello']"
    start_order_button_cssSelector = "div[class='col-sm-5 col-md-4 totals'] div[class='mb-sm-3']"
    shipping_type_xpath = "//*[contains(@id, 'shippingMethod-DHL002')]"
    name_shipping_id = "shippingFirstNamedefault"
    name_id = "Selene"
    surname_shipping_id = "shippingLastNamedefault"
    surname_id = "Palizzi"
    address_shipping_id = "shippingAddressOnedefault"
    address_id = "Via Quintino Sella, 10"
    zipcode_shipping_id = "shippingZipCodedefault"
    zipcode_id = "21052"
    phone_number_shipping_id = "shippingPhoneNumberdefault"
    phone_number_id = "3276131745"
    city_shipping_id = "shippingAddressCitydefault"
    city_id = "Busto Arsizio"
    birthday_date_id = "13/12/1989"
    accept_policy_privacy_cssSelector = "label[for='acceptprivacy']"
    privacy_checkbox_id = "acceptprivacy"
    continue_order_button_cssSlector = "button[value='submit-shipping']"
    payment_options_cssSelector = "#selectedPaymentOption"
    paypal_tab_cssSelector = ".paypal-tab"
    paypal_iframe_ecommerce_cssSelector = "iframe[name^='__zoid__paypal_buttons']"
    payment_paypal_button_cssSelector = "#buttons-container > div > div.paypal-button-row.paypal-button-number-0.paypal-button-layout-vertical.paypal-button-number-multiple.paypal-button-env-production.paypal-button-color-gold.paypal-button-text-color-black.paypal-logo-color-blue.paypal-button-shape-rect"
    # -------------------------------------------------------------------------------------
    # Locator - Paypal Payment
    paypal_email = "email"
    paypal_sandbox_account_email = "sb-ulsj935876751@personal.example.com"
    paypal_Accedi_button = "btnNext"
    paypal_password = "password"
    paypal_sandbox_account_password = "U!9SbCbC"
    paypal_login_button = "btnLogin"
    paypal_Modifica_button = "change-shipping"
    paypal_add_new_address = "add-option-shipping-link"
    paypal_address_box = "line1"
    paypal_new_address = "Viale Unità d'Italia, 57, Napoli"
    paypal_first_address = "EjJWaWFsZSBVbml0w6AgZCdJdGFsaWEsIDU3LCBTY2FmYXRpLCBOYXBvbGksIEl0YWxpYSIwEi4KFAoSCf2oIEiPvDsTEXG5O_ESf17GEDkqFAoSCT8rxk-RvDsTEcdsF4HLnYWf"
    paypal_save_address_button = "button[data-testid='add-shipping-save-btn']"
    paypal_paga_3_rate_view_details = "label[for='credit-offer-7013053529516968071'] span.xo-member-ea7h0y-check_icon_container"
    paypal_first_continue_button = "payment-submit-btn"
    paypal_second_continue_button = "submitButton"
    paypal_tax_number_locator = "fiscalCode"
    paypal_tax_number = "RSSMRA85T10A562S"
    paypal_phone_number_locator = "phoneNumber"
    paypal_phone_number = "3276131768"
    paypal_second_Modifica_button = "#addressCard > a"
    paypal_second_modify_address = "primaryAddressLine1"
    paypal_second_enter_new_address = "Viale Unità d'Italia, 57"
    paypal_postcode_locator = "primaryAddressPostcode"
    paypal_postcode = "84018"
    paypal_city_locator = "primaryAddressCity"
    paypal_city = "Scafati"
    paypal_Continue_button = "submitButton"
    paypal_select_Visa_card = '//p[text()="Visa"]/ancestor::button'
    paypal_flag_Paga_3_rate = 'input[data-testid="repaymentCheckbox"]'
    paypal_final_Continue_button = "payment-submit-btn"
    paypal_capcha_iframe = 'iframe[data-testid="cap-iframe"]'




